# Generated by Django 3.1.4 on 2020-12-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201214_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='listening',
            name='date',
            field=models.DateField(verbose_name='listening date'),
        ),
    ]
